sudo: true

jobs:
  include:
    - stage: Deploy Stable release on NPM
      sudo: false
      language: node_js
      node_js: 10

      install:
        - npm install

      deploy:
        provider: npm
        skip_cleanup: true
        email: support@kuzzle.io
	api_key:
	  secure: VWCnP7qr27FwPDi9u9qlJ80TeTJWrEIsWRnTifYTbs5sFlbgihaRsHVR9JCWCzJSAvgDNTP4lRytjuabwpOVMzlmWPzpjfcxqF16X1uj6RJPHo6FodWEhgRDPjo4LPacQxsgwjaqpnKj1X5oDAPDQusJCpQNF5oc8t8Sgf249gYaIhmkr2gdec8Ga48sqTNfG8r4jAzYRtJM+0x0StrZuAWUUqDnaKM6SZydMZ3l75VT6+V7ytIYLPhb0n5MgtB6lDm5o6eWwmmM9oC/W5fUq5oqHhay6fN/F6eRtzxtZBY0wePGZaeol+sD1kh4GeRsOLJMJThi2n5qCnkJkLLzmCJAjxf+UNwvG1ZtYBxj9+ZtfQaUhb5wcYtspz6PmbcXTZT9wpD90JtYULZqhTTP/P92XEMwh3gk+HE64VVWRxbRK3j993yfjgQbIu6nB6S6537mRkOmGfbUwiezyr5pSjnwtwj5J7OM/Imrqct1goX5peXRcZCAAbWUSA1HQZBOvzpz/EvTDAnXUsMb0bXCYRMJBL4xrsW/PTfXPxG+P0mVaJtwsBEUb9Mvw1jCRxf0Nh2mZTZcMbVWH03bYAUb6Nevn1bAxUrCo08L3L7rMRnhYwDTGshR4QZ4TkRGG8JeXQbAdidzus3zeYDEVnGFbDgCUu/7+XUIT0Vwa552vfA=
        on:
          repo: kuzzleio/vue-plugin-kuzzle
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^([0-9]+-stable|master)$
